## Numpy Tutorial

In [2]:
import numpy as np

### Array vs List

In [3]:
L = [1,2,3]
A = np.array([1,2,3])

In [4]:
L.append(4)

In [5]:
A.append(4)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

#### In numpy we can append like list bcz of memory allocation. 

In [ ]:
L + [5]

In [ ]:
A + np.array([4])

In [ ]:
# Looks like in numpy the value 4 is get added to each element insted it get appended. This process called
#Braodcasting
# Another thing to remember is that Numpy is mathetical opearation hence the + sign it understand as 
# addition opeartion not concatenation

In [ ]:
A + np.array([4,5,6]) #Element wise addition not Braodcasting of single value

In [ ]:
A + np.array([4,5]) #The above failure is expected as sum needs the dimension to be same size

In [ ]:
2 * A

In [ ]:
2 * L

In [ ]:
L + L

In [ ]:
# To square an array
#List
L**2

In [ ]:
L2 = []
for i in L:
    L2.append(i**2)
L2

In [ ]:
#Its super easy in Numpy
A**2

In [ ]:
#The mathematical function you apply on an numpy array always perform element wise

In [ ]:
print(np.log(A))
print(np.sqrt(A))
print(np.exp(A))
print(np.tanh(A)) #Hyperbolic Tangent

#### Note: A list look like an array but its more like a data struture while Numpy is more to math.

### Dot Product   
<img src="https://latex.codecogs.com/svg.image?a.b&space;=&space;a^{T}b=\sum_{d=1}^{D}a_{d}b_{d}" title="a.b = a^{T}b=\sum_{d=1}^{D}a_{d}b_{d}" />

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
np.dot(a,b)

In [ ]:
a*b

In [ ]:
c = np.array([1,2,3])
a*c #Dimention needs to be same in case of multiplication as it is element wise opn

In [ ]:
# Dot product is sum of element wise opn 
np.sum(a*b)

In [ ]:
a.dot(b)

In [ ]:
#Newer version of Numpy we can use @ symbol for dot opn
a @ b

In Linear algebra we can also right the dot product like below


<img src="https://latex.codecogs.com/svg.image?a.b&space;=&space;a^{T}b&space;=&space;\left\|&space;a\right\|\left\|&space;b\right\|&space;cos\theta&space;_{ab}" title="a.b = a^{T}b = \left\| a\right\|\left\| b\right\| cos\theta _{ab}" />

where

<img src="https://latex.codecogs.com/svg.image?\left\|&space;a\right\|&space;=&space;\sqrt{\sum_{d=1}^{D}}a{_{d}}^{2}" title="\left\| a\right\| = \sqrt{\sum_{d=1}^{D}}a{_{d}}^{2}" />

In [ ]:
a = np.array([1,2,3])
magnitude_a = np.sqrt(np.sum(np.square(a)))
magnitude_a

In [ ]:
magnitude_a = np.sqrt(np.sum(a*a))
magnitude_a

In [ ]:
# Numpy already has a function for it
np.linalg.norm(a)

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
magnitude_a = np.linalg.norm(a)
magnitude_b = np.linalg.norm(b)

In [ ]:
#As we know the magnitude of the vector we can find the cosine angle of vectors with dot product
cosangle = np.dot(a,b)/(magnitude_a * magnitude_b)
cosangle

In [ ]:
#To get the angle between vectors we can do arc cos
angle = np.arccos(cosangle)
angle #This angle is in randinace

In [ ]:
# SO there is a 0.17 radiance angle difference betwen vector a and b

### Matrices

In [ ]:
# There is bydefault numpy.matrix function but you should avoid using it


In [ ]:
# Matrix = List of Lists
L = [[1,2], [3,4]]
L

In [ ]:
row1 = L[0]
row1

In [ ]:
row2 = L[1]
row2

In [ ]:
#Numpy Matrix
A = np.array([[1,2],[3,4]])
A

In [ ]:
# Accessing rows of numpy matrix
A[0], A[1]

In [ ]:
A[0][1] , A[0,1]

In [ ]:
# Accessing columns of numpy matrix
A[:,0] # Accesses the values of column 0

In [ ]:
A[:,1]

In [ ]:
# Transpose
A.T

In [ ]:
#Applying a function to Matrix
np.exp(A)

In [ ]:
#Applying it to the list L. The numpy knows L is Listtype but it always returns a numpy array not list
np.exp(L)

In [ ]:
# Lets create a 2X3 matrix
B = np.array([[1,2,3],[4,5,6]])
B

In [ ]:
A

In [ ]:
#Matric multiplication means A.B
np.dot(A,B)

In [ ]:
# We cant do A*B as it will perform element wise opn and it will fail due to dimenstion mismatch

In [ ]:
print(f"A dimention: {A.ndim}")
print(f"B dimention: {B.ndim}")
print(f"A shape: {A.shape}")
print(f"B shape: {B.shape}")

In [ ]:
#We cant perform A.Transpose(B) due to shape mismatch
np.dot(A, B.T)

In [ ]:
# Inverse
np.linalg.inv(A)

In [ ]:
# Determitant
np.linalg.det(A)

In [ ]:
np.linalg.norm(A)

In [ ]:
#To cross check inverse is correct multiply the inverse result with original matrix and we should get indentity
np.dot(np.linalg.inv(A),A)

In [ ]:
#1.11022302e-16 is 0 
# Computers usually dont produce accurate inverse thats why we are seeing values with e
# So above matrix is actually like below
np.eye(2)

The trace of a square matrix is given by 

<img src="https://latex.codecogs.com/svg.image?\sum_{i=1}^{n}a_{ii}" title="\sum_{i=1}^{n}a_{ii}" />

where i = row count

In [ ]:
# Matrxi trace
# Trace of A = A[0,0] + A[1,1] = 1 + 4 = 5
np.trace(A), np.trace(B)

In [ ]:
# diag method is overloaded meanse if we pass a vector we will get a Matrix and vice versa
np.diag([2,3])

In [ ]:
np.diag(A)

### Eigen Vectors
<img src="https://latex.codecogs.com/svg.image?A&space;.&space;\underset{v}{\rightarrow}&space;=&space;\underset{v}{\rightarrow}&space;.&space;\lambda&space;" title="A . \underset{v}{\rightarrow} = \underset{v}{\rightarrow} . \lambda " />

A = Is a Matrix

v = eigen vector

Lambda = Eigen value

In [ ]:
# Eigen values
# It returns the eigen decomposition where 1st array is eigen value
# 2nd value is eigen vector in yerms of matrix
np.linalg.eig(A)

In [ ]:
# It retuns the 
lam , v = np.linalg.eig(A)
print("lambda", lam)
print("eigen vector", v)

In [ ]:
# The multiplication of 1st eigen value with 1st eigen vector should equal to
# multiplication of 1st eigen vector with Matrix A
print("1st lambda", lam[0])
print("1st column of eigen vector",v[:,0])

In [ ]:
#mult1 = lam[0] * v[:,0]
mult2 = A @ v[:,0] #Dot operation 
print(mult1)
print(mult2)

In [ ]:
mult1 == mult2

In [ ]:
# Although both values LOOKS similar but we are getting false because computer is storing either 32 or 64 bit of calcution
# and its rounding off if it crossing that value. Hence although the first few digit looks same may be last digits
# are different.

### Generating Data

In [6]:
# Uniform distribution
# Values beyween 0 and 1
np.random.random()

0.061020360325180656

In [7]:
np.random.random(10)

array([0.71232738, 0.01715328, 0.38084776, 0.35143981, 0.33609579,
       0.06219498, 0.74281218, 0.65510263, 0.02568153, 0.1289177 ])

In [8]:
np.random.random((2,3))

array([[0.7461471 , 0.2531106 , 0.83294277],
       [0.88772207, 0.60253205, 0.57863833]])

In [9]:
# Standard Normal distribution

In [10]:
np.random.randn()

0.11092902750936211

In [11]:
np.random.randn(10)

array([-1.72957675, -0.02216102, -0.56868171,  0.29856803, -1.59303874,
        0.2357869 ,  0.24809747, -0.65528083,  0.62270226, -0.63770322])

In [12]:
np.random.randn(2,3)

array([[-0.67013876,  0.08530868,  0.99184873],
       [-0.85155198,  0.00868597,  1.4392924 ]])

In [14]:
A = np.random.randn(3,3)
A

array([[-1.87151607, -0.53806957, -2.26987736],
       [-0.16956438, -1.53356106, -0.47139608],
       [ 0.4815258 ,  1.63313381, -0.57298444]])

In [16]:
A.mean(axis=1) # row mean

array([-1.559821  , -0.72484051,  0.51389172])

In [17]:
A.mean(axis=0) #Column mean

array([-0.51985155, -0.14616561, -1.10475263])

In [18]:
# Generating a random Positive int matrix
# Here it wil take 2-9
np.random.randint(2,10, size=(3,4))

array([[8, 9, 8, 6],
       [2, 8, 6, 2],
       [8, 8, 9, 2]])

In [19]:
# Same can be done via choice function
# Here 10 menas it will take 0-9
np.random.choice(10, size=(3,4))

array([[8, 7, 7, 9],
       [3, 3, 2, 0],
       [9, 1, 9, 4]])