### Loading the data

Pandas handels only structed data. It soes not support unstructured data like image, video etc.

In [2]:
import pandas as pd
df = pd.read_csv('data.csv')

In [3]:
type(df) #Its dataframe object not numpy array

pandas.core.frame.DataFrame

In [5]:
df.head(3)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [6]:
df.tail(3)

Country   Age   Salary Purchased
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


### Selecting rows and columns

simailar to numpy array indexing

In [9]:
# Check column names
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [10]:
#We can rename the columns
df.columns = ['country', 'age', 'salary', 'purchased']

In [11]:
df.columns

Index(['country', 'age', 'salary', 'purchased'], dtype='object')

In [12]:
df.head(3)

country   age   salary purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No

In [13]:
#To select multiple columns
df[['country', 'age']]

country   age
0   France  44.0
1    Spain  27.0
2  Germany  30.0
3    Spain  38.0
4  Germany  40.0
5   France  35.0
6    Spain   NaN
7   France  48.0
8  Germany  50.0
9   France  37.0

In [14]:
type(df['country']) #Its a series

pandas.core.series.Series

In [16]:
type(df[['country', 'age']]) # Its a dataframe

pandas.core.frame.DataFrame

For multiple colmns it becomes a dataframe and for single its a series. for a 2D its a dataframe.

Usually in Numpy we select the rows using square bracket but here in pandas we are using this for column selection.

In [18]:
import numpy as np
a = np.array([[11,2,3],[4,5,6]])
a, a[1]

(array([[11,  2,  3],
        [ 4,  5,  6]]),
 array([4, 5, 6]))

In [19]:
#Selecting rows of a dataframe (WIll use loc or iloc)
# Getting 0th row data
df.iloc[0]

country       France
age             44.0
salary       72000.0
purchased         No
Name: 0, dtype: object

In [20]:
df.loc[0]

country       France
age             44.0
salary       72000.0
purchased         No
Name: 0, dtype: object

In [21]:
# iloc is used for integer indices where as loc uses the index labels.

In [24]:
# Loading a dataframe using one of the coulmn as index
df2 = pd.read_csv('data.csv', index_col='age') 
# This one throws error as age column is not unique

ValueError: Index age invalid

In [25]:
# Selecting multiple rows
df[df['age']>30]

country   age   salary purchased
0   France  44.0  72000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [35]:
df[(df['age']>30) & (df['purchased']=='Yes')]

country   age   salary purchased
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
9   France  37.0  67000.0       Yes

In [31]:
# How to convert a dataframe into a numpy array as most ML models process the arrays
df.values 

array([['France', 44.0, 72000.0, 'No'],
       ['Spain', 27.0, 48000.0, 'Yes'],
       ['Germany', 30.0, 54000.0, 'No'],
       ['Spain', 38.0, 61000.0, 'No'],
       ['Germany', 40.0, nan, 'Yes'],
       ['France', 35.0, 58000.0, 'Yes'],
       ['Spain', nan, 52000.0, 'No'],
       ['France', 48.0, 79000.0, 'Yes'],
       ['Germany', 50.0, 83000.0, 'No'],
       ['France', 37.0, 67000.0, 'Yes']], dtype=object)

In [33]:
# The above type was dtype object because it alos contains the strings
# To selct only numerical array
A = df[['age','salary']].values
A

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01,     nan],
       [3.5e+01, 5.8e+04],
       [    nan, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [34]:
type(A)

numpy.ndarray